# Generated by Django 4.0.10 on 2026-02-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalIbadah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ibadah', models.CharField(max_length=100)),
                ('hari', models.CharField(max_length=30)),
                ('jam', models.CharField(max_length=50)),
                ('tempat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPelayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis_ibadah', models.CharField(max_length=100)),
                ('pelayan_altar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilGereja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gereja', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('kota', models.CharField(max_length=100)),
                ('no_telpon', models.CharField(max_length=20)),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Renungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('perikop', models.TextField()),
                ('isi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rhema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WartaGereja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
