# Generated by Django 4.0.10 on 2026-02-14 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgbt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwalpelayanan',
            old_name='pelayan_altar',
            new_name='nama_ibadah',
        ),
        migrations.RemoveField(
            model_name='jadwalibadah',
            name='hari',
        ),
        migrations.RemoveField(
            model_name='jadwalibadah',
            name='jam',
        ),
        migrations.AddField(
            model_name='jadwalibadah',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='galeri/'),
        ),
        migrations.AddField(
            model_name='jadwalibadah',
            name='jenis_ibadah',
            field=models.CharField(choices=[('minggu', 'Ibadah Minggu'), ('komsel', 'komsel'), ('pondok daud', 'Ibadah Daud'), ('hari besar', 'Ibadah Hari Besar')], default='minggu', max_length=20),
        ),
        migrations.AddField(
            model_name='jadwalibadah',
            name='tanggal',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalpelayanan',
            name='bassist',
            field=models.CharField(default='belum ditentukan', max_length=50),
        ),
        migrations.AddField(
            model_name='jadwalpelayanan',
            name='gitaris',
            field=models.CharField(default='belum ditentukan', max_length=50),
        ),
        migrations.AddField(
            model_name='jadwalpelayanan',
            name='kajon_atau_drum',
            field=models.CharField(default='belum ditentukan', max_length=50),
        ),
        migrations.AddField(
            model_name='jadwalpelayanan',
            name='keyboardis',
            field=models.CharField(default='belum ditentukan', max_length=50),
        ),
        migrations.AddField(
            model_name='jadwalpelayanan',
            name='multimedia',
            field=models.CharField(default='belum ditentukan', max_length=50),
        ),
        migrations.AddField(
            model_name='jadwalpelayanan',
            name='pembawa_firman',
            field=models.CharField(default='belum ditentukan', max_length=50),
        ),
        migrations.AddField(
            model_name='jadwalpelayanan',
            name='singer',
            field=models.CharField(default='belum ditentukan', max_length=100),
        ),
        migrations.AddField(
            model_name='jadwalpelayanan',
            name='worship_leader',
            field=models.CharField(default='belum ditentukan', max_length=50),
        ),
        migrations.AlterField(
            model_name='jadwalpelayanan',
            name='jenis_ibadah',
            field=models.CharField(choices=[('minggu', 'Ibadah Minggu'), ('komsel', 'komsel'), ('pondok daud', 'Ibadah Daud'), ('hari besar', 'Ibadah Hari Besar')], default='minggu', max_length=20),
        ),
        migrations.AlterField(
            model_name='jadwalpelayanan',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wartagereja',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Simpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('disimpan_pada', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
