# Generated by Django 4.0.10 on 2026-02-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0002_rename_pelayan_altar_jadwalpelayanan_nama_ibadah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalpelayanan',
            name='tanggal',
            field=models.CharField(default='belum ditentukan', max_length=20),
        ),
    ]
