# Generated by Django 4.0.10 on 2026-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0003_alter_jadwalpelayanan_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalibadah',
            name='jenis_ibadah',
            field=models.CharField(choices=[('minggu', 'Ibadah Minggu'), ('komsel', 'komsel'), ('pondok daud', 'Pondok Daud'), ('hari besar', 'Ibadah Hari Besar'), ('ibadah anak', 'Ibadah Anak')], default='minggu', max_length=20),
        ),
        migrations.AlterField(
            model_name='jadwalpelayanan',
            name='jenis_ibadah',
            field=models.CharField(choices=[('minggu', 'Ibadah Minggu'), ('komsel', 'komsel'), ('pondok daud', 'Pondok Daud'), ('hari besar', 'Ibadah Hari Besar'), ('ibadah anak', 'Ibadah Anak')], default='minggu', max_length=20),
        ),
        migrations.AlterField(
            model_name='jadwalpelayanan',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
