# Generated by Django 4.2.28 on 2026-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0005_suka_bagikan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagikan',
            options={'verbose_name': 'Bagikan', 'verbose_name_plural': 'Bagikan'},
        ),
        migrations.AlterModelOptions(
            name='jadwalibadah',
            options={'verbose_name': 'Jadwal Ibadah', 'verbose_name_plural': 'Jadwal Ibadah'},
        ),
        migrations.AlterModelOptions(
            name='jadwalpelayanan',
            options={'verbose_name': 'Jadwal Pelayanan', 'verbose_name_plural': 'Jadwal Pelayanan'},
        ),
        migrations.AlterModelOptions(
            name='komentar',
            options={'verbose_name': 'Komentar', 'verbose_name_plural': 'Komentar'},
        ),
        migrations.AlterModelOptions(
            name='profilgereja',
            options={'verbose_name': 'Profil Gereja', 'verbose_name_plural': 'Profil Gereja'},
        ),
        migrations.AlterModelOptions(
            name='renungan',
            options={'verbose_name': 'Renungan', 'verbose_name_plural': 'Renungan'},
        ),
        migrations.AlterModelOptions(
            name='rhema',
            options={'verbose_name': 'Rhema', 'verbose_name_plural': 'Rhema'},
        ),
        migrations.AlterModelOptions(
            name='simpan',
            options={'verbose_name': 'Simpan', 'verbose_name_plural': 'Simpan'},
        ),
        migrations.AlterModelOptions(
            name='suka',
            options={'verbose_name': 'Suka', 'verbose_name_plural': 'Suka'},
        ),
        migrations.AlterModelOptions(
            name='wartagereja',
            options={'verbose_name': 'Warta Gereja', 'verbose_name_plural': 'Warta Gereja'},
        ),
    ]
