# Generated by Django 4.2.28 on 2026-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0006_alter_bagikan_options_alter_jadwalibadah_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhema',
            name='perikop',
            field=models.CharField(default='belum ditentukan', max_length=200),
        ),
        migrations.AlterField(
            model_name='renungan',
            name='perikop',
            field=models.CharField(default='belum ditentukan', max_length=200),
        ),
    ]
