# Generated by Django 4.2.28 on 2026-03-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0007_rhema_perikop_alter_renungan_perikop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilGereja',
        ),
    ]
