# Generated by Django 4.2.28 on 2026-04-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0008_delete_profilgereja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rhema',
        ),
    ]
