# Generated by Django 4.2.28 on 2026-04-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0009_delete_rhema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwalibadah',
            old_name='nama_ibadah',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='jadwalpelayanan',
            old_name='nama_ibadah',
            new_name='nama',
        ),
    ]
