# Generated by Django 4.2.28 on 2026-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0010_rename_nama_ibadah_jadwalibadah_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renungan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='galeri/'),
        ),
    ]
