# Generated by Django 4.2.28 on 2026-05-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0011_renungan_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='baptis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=20)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='baptis/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
