# Generated by Django 4.2.28 on 2026-05-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0012_baptis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelayanAltar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=20)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('bidang_pelayanan', models.CharField(choices=[('Singer', 'Singer'), ('Music', 'Music'), ('Multimedia', 'Multimedia'), ('Usher', 'Usher'), ('Doa', 'Doa'), ('Tamborin', 'Tamborin')], max_length=50)),
                ('pengalaman', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
