# Generated by Django 4.2.28 on 2026-05-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0013_pelayanaltar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baptis',
            name='foto',
        ),
        migrations.AddField(
            model_name='baptis',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
