# Generated by Django 4.2.28 on 2026-05-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0014_remove_baptis_foto_baptis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelayanaltar',
            name='email',
        ),
    ]
