# Generated by Django 4.2.28 on 2026-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0015_remove_pelayanaltar_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPelayanAltar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bidang_pelayanan', models.CharField(choices=[('Singer', 'Singer'), ('Music', 'Music'), ('Multimedia', 'Multimedia'), ('Usher', 'Usher'), ('Doa', 'Doa'), ('Tamborin', 'Tamborin'), ('Sekolah Minggu', 'Sekolah Minggu')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pelayanaltar',
            name='bidang_pelayanan',
            field=models.CharField(choices=[('Singer', 'Singer'), ('Music', 'Music'), ('Multimedia', 'Multimedia'), ('Usher', 'Usher'), ('Doa', 'Doa'), ('Tamborin', 'Tamborin'), ('Sekolah Minggu', 'Sekolah Minggu')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Bagikan',
        ),
    ]
