# Generated by Django 4.2.28 on 2026-05-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0017_alter_datapelayanaltar_bidang_pelayanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapelayanaltar',
            name='bidang_pelayanan',
            field=models.CharField(choices=[('Worship Leader', 'Worship Leader'), ('Pembawa Firman', 'Pembawa Firman'), ('Singer', 'Singer'), ('Music', 'Music'), ('Multimedia', 'Multimedia'), ('Usher', 'Usher'), ('Tamborin', 'Tamborin'), ('Sekolah Minggu', 'Sekolah Minggu')], max_length=50),
        ),
    ]
