# Generated by Django 4.2.28 on 2026-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0018_alter_datapelayanaltar_bidang_pelayanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptis',
            name='jadwal_baptis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baptis',
            name='lokasi_baptis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('diterima', 'Diterima')], default='draft', max_length=20),
        ),
    ]
