# Generated by Django 4.2.28 on 2026-05-29 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgbt', '0019_baptis_jadwal_baptis_baptis_lokasi_baptis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komentar',
            options={'ordering': ['-dibuat_pada'], 'verbose_name': 'Komentar', 'verbose_name_plural': 'Komentar'},
        ),
        migrations.AddField(
            model_name='komentar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balasan', to='webgbt.komentar'),
        ),
    ]
